---
- name: "gather vpn information"
  ec2_vpc_vpn_facts:
    aws_secret_key: "{{ aws_secret_key }}"
    aws_access_key: "{{ aws_access_key }}"
    region: "{{ region }}"
  when:
    - aws_secret_key is defined
    - aws_secret_key is defined
    - region is defined
  register: result_vpn

- name: "gather vpn information"
  ec2_vpc_vpn_facts:
    aws_secret_key: "{{ aws_secret_key }}"
    aws_access_key: "{{ aws_access_key }}"
    region: "{{ region }}"
    vpn_connection_ids: "{{ result_vpn | json_query('vpn_connections[].vpn_connection_id') | join(',') }}" # "{{ vpn_connection_ids }}"
  when:
    - aws_secret_key is defined
    - aws_secret_key is defined
    - region is defined
  register: results

- debug:
    msg: "VPN connection ip address Down - {{item.outside_ip_address}}"
  when: item.status == 'DOWN' and  result_vpn is succeeded
  with_items: "{{ results | json_query('vpn_connections[].vgw_telemetry[]') }}"
  register: vpn_result
  no_log: true

- name: "Mail ec2 vpn information"
  mail:
    host: "{{smtp_host}}" # smtp.gmail.com
    port: "{{smtp_port}}" # 587
    username: "{{smtp_username}}"
    password: "{{smtp_password}}"
    to: "{{email_to}}"
    cc: "{{email_cc}}"
    # from: "ansible@{{ansible_nodename}}"
    subject: "{{ client_name }} ec2 vpn DOWN Report"
    body: "{{vpn_result.results | json_query('[].msg')}}"          # "VPN connection {{item.outside_ip_address}} is down"
  delegate_to: "{{ delegate_host | default('localhost') }}"
  run_once: True
  when: results.vpn_connections != [] and result_vpn is succeeded and mail_alert == true

- name: "Send notification message via Slack"
  slack:
    token: "{{slack_token}}"
    channel: "{{ansible_slack_channel}}"
    msg: "{{vpn_result.results | json_query('[].msg') | replace('[]', '')}}" # "VPN connection ip address Down - {{item.outside_ip_address}}"
  when: results.vpn_connections != [] and result_vpn is succeeded and slack_alert == true
