---
- name: "Security Check"
  hosts: zabbix
  vars_prompt:
  - name: LINUX_SERVER
    prompt: "Which linux server do you want to deploy?\n1 - Security Check\n2 - Existing server\n"
    private: no
  tasks:
  roles:
    - role: cloudnloud_security
