---
- name: "gather vpn information"
  hosts: localhost
  roles:
  - role: ec2_vpn_monitor
    delegate_host: localhost
    email_to: support@skylarkinfo.com
    email_cc: darmesh@skylarkinfo.com,navaneethan@skylarkinfo.com,selva@skylarkinfo.com,navaneethan@skylarkinfo.com
    #aws_access_key: AKIA6DTHLTSBJZH5LJTZ
    #aws_secret_key: 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
    region: us-east-1
    mail_alert: true
    slack_alert: false
    smtp_host: smtp.gmail.com
    smtp_port: 587
    smtp_username: monitoring@skylarkinfo.com
    template_storage_path: /home/ansible/vpn_monitor.txt
 
