---
- name: "the vpn down status"
  hosts: localhost
  roles:
    - role: ec2_vpn_down_alert
      delegate_host: localhost
      email_to: support@skylarkinfo.com
      email_cc: navaneethan@skylarkinfo.com,selva@skylarkinfo.com,darmesh@skylarkinfo.com,nilober@skylarkinfo.com
      template_storage_path: /tmp/ec2_vpn_info.txt
      client_name: Skylark
      slack_alert: false
      mail_alert: true
      smtp_host:  smtp.gmail.com
      smtp_port: 587
      smtp_username: monitoring@skylarkinfo.com
      region: us-east-1
