---
- hosts: localhost
  tasks:
  - name: "VPN Information"
    ec2_vpc_vpn_facts:
      aws_secret_key: noNNdcpUzR45VZ/0bnfwx4D7Holk993YLc7GS0z5
      aws_access_key: AKIA6DTHLTSBJZH5LJTZ
      region: us-east-1
      vpn_connection_ids: 
        - vpn-0c32629592ec70968
      # filters:
      #  vpn-gateway-id: vgw-0832a847f2998ae2c
    register: results

  - name: "template for vpn monitering"
    template:
      src: skylark_vpn_monitering_template.j2
      dest: /tmp/sky_vpn_info.txt
